version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: CourseManagement
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: course_management
    ports:
      - '3310:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: